### ISSUE TITLE
With removing the support for column quoting, relational databases with upper case column names are not supported at soda checks

### ISSUE THREAD

**Issue by bonisb** [datacontract/cli#119]
Due to these two changes relational databases (like postgres/mysql) lost the support for uniqueness and required checks on columns with uppercase character: 
- https://github.com/datacontract/cli/pull/28
- https://github.com/datacontract/cli/commit/8d42764b3f4c78ac6955745221756c4e8c90756b

Particularly due to these changes: https://github.com/datacontract/cli/commit/8d42764b3f4c78ac6955745221756c4e8c90756b#diff-7ea6d7633102558be6b4b011c4aaaab88e72dfbfe81e63793c7d45335d00e979L63

An example of this issue:
```
2024-03-26 20:11:50.311 WET [16061] HINT:  Perhaps you meant to reference the column "test_table.camelCase".
2024-03-26 20:11:50.311 WET [16061] STATEMENT:  SELECT 
	  COUNT(CASE WHEN id IS NULL THEN 1 END),
	  COUNT(CASE WHEN camelCase IS NULL THEN 1 END)
	FROM public.test_table
ERROR:soda.scan:[20:11:50] Query execution error in postgres.test_table.aggregation[0]: column "camelcase" does not exist
```

As this postgresql query would require the quoting around the "camelCase".

**Comment by jochenchrist** [comment]
Thanks for reporting.
I will investigate.

**Comment by jochenchrist** [comment]
Quoting or not makes a difference with some server types (BigQuery won't work anymore...)
I introduced a flag, so postgres server type should now work.

Do you have a chance to validate it with the latest main branch?

**Comment by bonisb** [comment]
@jochenchrist yes, it's working with the latest!
