### ISSUE TITLE
IMPORT - doc required and namespace unsupported

### ISSUE THREAD

**Issue by gpthome** [datacontract/cli#121]
Two observations running this command `datacontract import --format avro --source sampleValue.avsc
` using the below AVRO example

```
{
    "type": "record",
    "name": "SampleValue",
    "doc": "Some comments in the doc attribute.",
    "namespace": "com.sample.schema",
    "fields": [
        {
            "name": "customer_no",
            "type": {
                "type": "string",
                "avro.java.string": "String"
            }
        },
        {
            "name": "acquired_dt",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
            }
        }
    ]
}
```

1. The "doc" attribute seems to be required by the CLI import command.  The command fails without it.  From a practical perspective, I didn't know this field existed until the CLI failed and I looked up possible attributes.  I see [here](https://avro.apache.org/docs/1.11.1/specification/#schema-record) this field is optional.
2. "namespace" attribute seems to be ignored by the CLI import command.  I hope for it to be part of the import because I need it to be part of the EXPORT that I use as input into a Java code generation flow.  It's the Java class package.  I don't see a corresponding element in [your doc](https://datacontract.com/#model-object), so maybe it's not supported or I'm approaching this incorrectly.

<img width="406" alt="image" src="https://github.com/datacontract/cli/assets/5378257/660f0b4b-d022-4425-bd13-f13ce54f1573">

Thanks!

**Comment by jochenchrist** [comment]
Hi @gpthome,

thanks for reporting.

1. I'd assume, this is a bug. We will have a check.
2. "namespace" is currently not mapped, but I think it makes sense to add it.

**Comment by gpthome** [comment]
Thank you.  I pulled down the changes and ran import and export commands.  The "doc" is optional now and the "namespace" from the avsc source file  is now recognized.  Thank you!

```
dataContractSpecification: 0.9.3
id: my-data-contract-id
info:
  title: My Data Contract
  version: 0.0.1
models:
  SampleValue:
    type: table
    namespace: com.sample.schema
    fields:
      customer_no:
        type: string
        required: true
      acquired_dt:
        type: long
        required: true
```

However, when I add the "namespace" to the datacontract.yaml and run `datacontract export --model SampleValue --format avro `, the "namespace" is missing.  That is used by Java code generators.  The namespace is turned in the Java class package.  Do we need a separate issue for that?

```
{
  "type": "record",
  "name": "SampleValue",
  "namespace": "com.sample.schema",   <= MISSING
  "fields": [
    {
      "name": "customer_no",
      "type": "string"
    },
    {
      "name": "acquired_dt",
      "type": "long"
    }
  ]
}
```
