### ISSUE TITLE
Lint with custom specificaition

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/cli#130]
Hello, 

In the previous version of the CLI, it was possible to use the lint command with a custom specification defined in JSON. Is it something you plan to add ? 

`datacontract lint --specification https://my_custom_spec.json`

**Comment by saugerDecathlon** [comment]
It is mostly for adding new required information in a contract ("e.g. an url associated to a contract)

**Comment by simonharrer** [comment]
It should still work using the schema option.

**Comment by jochenchrist** [comment]
```
datacontract lint --schema https://datacontract.com/datacontract.schema.json datacontract.yaml
```

should work.
Or am I missing the point here?

**Comment by saugerDecathlon** [comment]
Indeed, my bad it was a version conflict on my side. I am closing this issue. Thanks for the quick answers
