### ISSUE TITLE
datacontract export --format html

### ISSUE THREAD

**Issue by JohannesKonings** [datacontract/cli#15]
Are there any plans to generate the contract as HTML for self hosting as an alternative to https://studio.datacontract.com/?
Something like redoc cli: https://redocly.com/docs/redoc/deployment/cli/

Thanks

**Comment by stefannegele** [comment]
Hi @JohannesKonings 
We currently have no concrete plans for this, but I can definitely see the added value that this feature would offer. However, other features relating to data contract enforcment are currently prioritized higher.

**Comment by jochenchrist** [comment]
I like this idea.

Could be something like:
```
datacontract export --format html
```

**Comment by jochenchrist** [comment]
Should be implemented with react to be integrable with Backstage.

Similar to this:
https://github.com/backstage/backstage/tree/master/plugins/api-docs

**Comment by stefannegele** [comment]
I'm not so sure if we should mix this. I would propose to have a separate backstage type which wraps the output into a react component and keep the html output static and without any JavaScript dependencies if possible.

**Comment by saugerDecathlon** [comment]
I am really interested by this feature as well. It could be useful in my projects to serve a GitHub Pages illustrating the contracts in its associated repo

**Comment by jochenchrist** [comment]
I added the first version of an HTML export.

Not complete, as some formats, definitions and service levels are still missing, but should be good enough for an early version.
