### ISSUE TITLE
Validate-quality-object question

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/cli#2]
Hi, 

Really nice project. How did you plan to integrate the validate-quality-object ? I would be happy to help on this part.

Simon AUGER

**Comment by simonharrer** [comment]
It's basically a validation of the given quality specification. E.g., when someone is using SodaCL, we should validate the sodacl specification. We're happy to get contributions here. 

Our plan:
- Use validation offered by the vendor of the quality specification, e.g., soda, montecarlo, etc.
- If there is nothing offered by the vendor, implement the validation on our own to catch 80% of the issues using either JSON Schema validation or validation directly in Go.

Does this help you to get going? What would you plan to tackle?

**Comment by saugerDecathlon** [comment]
Thanks for the answer. So we could for example reference (using the $ref) a great expectation json file. And the validate method would trigger the expectation validation ?

**Comment by stefannegele** [comment]
We just discussed this internally, and are now planning to rename "validate" to "lint" to make the purpose clearer.
The --validate-quality-object (or better --include-quality-object) would just check if the quality checks have the correct format, without any actual execution of the quality checks themselves.

To trigger the defined quality checks in an external tool, like great expectation, is something for a different command. We want to name that "test". We are happy about any contributions, if you want to take a shot!

**Comment by saugerDecathlon** [comment]
Ok perfect ! Indeed it is clearer. I will work on my side to add the "test" feature working with some quality tools (such as great expectation and dbt test) and open a PR on your project when I have something that work 😃

**Comment by stefannegele** [comment]
Nice! Looking forward to this!

**Comment by simonharrer** [comment]
Awesome. Looking forward to your contribution. Feel free to open a PR with WIP status even before it is done if you want to get feedback early on.

**Comment by da115115** [comment]
* PR created: https://github.com/datacontract/cli/pull/3
* Very early work (WIP). Do not merge it right now. I submitted the PR so that several of us (_e.g._, [Simon](https://github.com/saugerDecathlon)) can collaborate on it
