### ISSUE TITLE
Lint Contract

### ISSUE THREAD

**Issue by simonharrer** [datacontract/cli#4]
- Liniting should check that documentation best practices are met
- Warn if one uses constraints like "maximum" on a non-number-type.

**Comment by simonharrer** [comment]
A few ideas: (perhaps interesting for you @jeeger)
- Warn if noticePeriod is not a duration
- Warn if one uses constraints like "maximum" on a non-number-type.
- Warn if the pattern is not a valid regex (try to compile it)

**Comment by simonharrer** [comment]
- If a field is primary, it also needs to be unique and required.

**Comment by simonharrer** [comment]
That „references: orders.order_id“ points to am existing field in the model.

**Comment by jochenchrist** [comment]
Closing issue, as @jeeger contributed more linters with #71. 
Let's open specific issues for additional linter functionality.
