### ISSUE TITLE
Lint - Support local schema

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/cli#46]
It would be great to have the option to specify a local schema path for the lint command.
Background: At my company, we've customized our Contract Specifications, and I would like to validate my model against this tailored specification

**Comment by jochenchrist** [comment]
@saugerDecathlon 

Could you please check, if the implementation works as expected, before I create a new release:

```
git clone git@github.com:datacontract/cli.git
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools wheel
pip install -e '.[dev]' 
```

and run

```
datacontract --schema <your_schema_file lint <your_datacontract_yaml>
```

**Comment by saugerDecathlon** [comment]
@jochenchrist 
Hi, 

This command does not work 

`datacontract lint <your_datacontract_yaml>  --schema <your_schema_file>`

But this one works:

`datacontract   lint <your_datacontract_yaml> <your_schema_file>`

So it depends if you want the schema to be a named parameter or not. But for me it is fine 

Thanks

**Comment by jochenchrist** [comment]
@saugerDecathlon Thanks for testing and reporting the bug.

https://github.com/datacontract/cli/commit/28a2f3e9a128805052f5116e1287feb0f7074d3d
should introduce the option as intended.
