### ISSUE TITLE
Adding Great Expectations support

### ISSUE THREAD

**Issue by saugerDecathlon** [datacontract/cli#47]
Adding Great Expectations support alongside the existing Soda support for the test command would be nice

**Comment by jochenchrist** [comment]
Hi @saugerDecathlon.

The concept of datacontract CLI is to support multiple engines (soda-core, great expectations, JSON Schema, ...). 
Based on the server.type, the defined model attributes and the defined quality checks, the CLI chooses the engines that are suited for the tests to run. datacontract CLI then gives a consolidated result.

For now, most checks are feasible using soda-core and their adapters.

Could you provide some more details about your use case that should be performed with great expectations?

**Comment by saugerDecathlon** [comment]
Hi @jochenchrist, thank you for the answer. My use case would be the following 
- enable an `export --format great-expectations` to generate expectations_suite.json file from the contract schema 
- add great expectations engines for the `datacontract test` command in addition of soda

**Comment by saugerDecathlon** [comment]
> I second this.
> 
> @saugerDecathlon Do you have time and interest to contribute this?

Yes

**Comment by simonharrer** [comment]
Implemented in #92

**Comment by jochenchrist** [comment]
Closing thins issue, as implemented in #92
