### ISSUE TITLE
export --format sql

### ISSUE THREAD

**Issue by simonharrer** [datacontract/cli#55]
```
datacontract export --format sql
```

should create a SQL DDL statement, that matches the server.type SQL dialect.

**Comment by jankatins** [comment]
I would also love to see that the checks get exported as plain SQL queries, e.g. by returning either "nothing" if passing or true/false.

**Comment by jochenchrist** [comment]
@jankatins 
Great idea! I would propose a separate export format:

```
datacontract export --format sql-tests
```

**Comment by simonharrer** [comment]
I've implemented export to sql-ddl and sql-query. Closing this for now. Feel free to reopen if you want to continue the discussion on the sql-tests export idea.
