### ISSUE TITLE
Exporting scan results

### ISSUE THREAD

**Issue by pluttgens** [datacontract/cli#64]
Hi, recently stumbled upon this project that looks very promising. 

Would having a feature to export scan results to a file or a SQL table for example fit the scope of this project ?

In my case, I have to be able to perform little more complex tasks than simply testing the data contract, such as only validating selected models from it (for dev purpose, otherwise it can cost too much in time and money) and exporting the results locally in dev and in a snowflake table in production for monitoring/support purposes.

**Comment by jochenchrist** [comment]
What probably is a good idea is to add the `diagnostics` information into the run results.
