### ISSUE TITLE
Push metrics after a test run to open telemetry

### ISSUE THREAD

**Issue by simonharrer** [datacontract/cli#77]
```
datacontract test --publish https://asdf.apm.westeurope.azure.elastic-cloud.com:443 --format opentelemetry
```

This should send the total result as a metric.

**Comment by tarys** [comment]
Does this mean that any monitoring system that supports OpenTelemetry could be used and not only Azure?

**Comment by simonharrer** [comment]
The URL is just an example. You should be able to push it to any system that speaks the open telemetry protocol.

**Comment by DGuhr** [comment]
https://github.com/datacontract/cli/compare/main...DGuhr:cli:otel_integration_hack?expand=1 on this branch is a first, very hacky implementation for inspiration / as a starting point (i don't know python nor the cli structure well, I just wanted to see if it works the way I thought it should). It emits metrics once to the console for now. Inspiration from this PR: https://github.com/open-telemetry/opentelemetry-python/pull/3059 

I thought id, version and title might be good dimensions to visualize/filter, but everything is open to discussion for sure.

Picture of the current result:
<img width="1477" alt="Bildschirmfoto 2024-03-09 um 19 56 19" src="https://github.com/datacontract/cli/assets/89905860/d2e010cd-12b0-4685-98e1-2648e1995732">

**Comment by DGuhr** [comment]
https://gist.github.com/DGuhr/62699b7462c28f7b73f734f1b4b32920 here's a gist to get you started if you want to run a local observability stack to check the behaviour. We'd love to get feedback :)
