### ISSUE TITLE
Enhance Breaking

### ISSUE THREAD

**Issue by torbenkeller** [datacontract/cli#81]
Breaking already has the basic functionality, but still lacks some feature:

- [ ] different output formats. oasdiff supports `json`, `yaml`, `html`, `githubactions` and `junit`. The CLI should also support at least `junit`
- [ ] ignore specific breaking changes. In oasdiff you can specify configuration files for that. [Documentation](https://github.com/Tufin/oasdiff/blob/main/BREAKING-CHANGES.md#ignoring-specific-breaking-changes)
- [ ] option to activate / deactivate returning error code 1 on warnings and errors

**Comment by jochenchrist** [comment]
Thanks for listing these open topics.

We prefer not to have multiple tasks tickets, as they are difficult to track.
I am closing this issue, please open individual issues when working on one of the features.
