### ISSUE TITLE
Code quality tools

### ISSUE THREAD

**Issue by lukland** [datacontract/cli#86]
Hi,
Is it planned to use code quality tools like Ruff, Pylint, isort etc.? In order to follow common Python conventions.
I've seen that Flake8 is used in the `.github/workflows/ci.yaml` workflow, but it seems to be a bit light. 
I would like to discuss with you about it and help if I can.

**Comment by simonharrer** [comment]
We're happy for any contribution. We try to get this new open source tool off the ground, and get adoption and features. Supporting code quality tools is helpful if they detect bugs or prevent them, but we don't want to comb through false positives. If you want to contribute there, feel free. :-)

**Comment by jochenchrist** [comment]
+1 for Ruff or Black.

**Comment by jochenchrist** [comment]
Added ruff check as Github action and updated the README to use ruff format.
