### ISSUE TITLE
Set dev version when not releasing

### ISSUE THREAD

**Issue by da115115** [datacontract/cli#9]
Currently, the version is hard-coded in a few places and is kept as the last [release version/tag](https://github.com/datacontract/cli/tags), mainly in the [`main.go` source code file](https://github.com/datacontract/cli/blob/main/main.go#L43) and the [`README.md` documentation file](https://github.com/datacontract/cli/blob/main/README.md).

I would suggest to bump the current version, in at least the [`main.go` source code file](https://github.com/datacontract/cli/blob/main/main.go#L43), to something reminding that it is a development version, distinguishing it from the released version, _e.g._, `99.99.99` or `0.3.1.rc1`.

To expose more specifically the issue:
1. Install `datacontract` from https://github.com/datacontract/cli/releases . Then, `datacontract --version` yields `v0.3.0`, which is good, as expected
2. Build locally `datacontract`, with something like `go build -o datacontract`. Then, `./datacontract --version` yields again `v0.3.0`, which is not so good, as `./datacontract` is the development binary, and is therefore clearly different in principle from the v0.3.0 release of `datacontract`. I would expect that `./datacontract --version` rather yields `v0.3.1.rc1`, `v99.99.99` or something similar.

**Comment by stefannegele** [comment]
We will use the next minor version and append -dev for now.
https://github.com/datacontract/cli/commit/1e2be619c8f9e6267049b5085f2349307f0ffae1#diff-7b5cd177b2ffeb83c4058016b16c6bf779bac2ea6af4f301841918178c4ada22R52
